

# ----------------------------------------------------------------------------------------------------------------
# get raw data as template 
data = CSV.read("./../output/data_processed.csv",DataFrames.DataFrame);

# get GP output for fitting 
pred_dir = "./../output/gp/data" # CHECK 
data_gp = CSV.read(pred_dir*"/preds.csv",DataFrame);
data = data[data.length .>=9,:]
lineages = unique(data.lineage);
lineages

# get fitted params generated by fitting.jl
d_fits = CSV.read("./../output/fitted_params.csv",DataFrame)
d_fits[:,:t_OU] = 1 ./d_fits[:,:γ_OU];
d_fits[:,:t_DN] = 1 ./d_fits[:,:γ_DN];

# ----------------------------------------------------------------------------------------------------------------
# 
nreps = 10
sims = []
global k = 1
for lin in lineages
    println("replicating lineage "*string(lin)*"--------------")
    # -----------------------------------------------------------
    df_gp = data_gp[data_gp.lineage .==lin,:]
    df = data[data.lineage .==lin,:]
    D = d_fits[d_fits.lineage .==lin,:D][1]
    τOU = 1/d_fits[d_fits.lineage .==lin,:γ_OU][1]
    τDN = 1/d_fits[d_fits.lineage .==lin,:γ_DN][1]
    Δ = d_fits[d_fits.lineage .==lin,:Δ][1]
    λ0 = d_fits[d_fits.lineage .==lin,:λ0][1]
    σM = d_fits[d_fits.lineage .==lin,:σM][1]
    σDN = sqrt(d_fits[d_fits.lineage .==lin,:σ2][1])

    for i in ProgressBar(1:nreps)
        # -----------------------------------------------------------
        # OU Model
        # build model and run 
        θ = (Δ = Δ, σDN=0,τ = τOU,D=D ,λ0 = λ0, σM = σM)
        println("    θ = ",θ)
        init = [θ.Δ,θ.λ0,2*θ.Δ]
    
        prob,callback,names = GrowthTraceTools.build_model_OU(θ,init,df.time)
        sol = solve(prob,EM(),callback = callback);

        
        # put in dataframe 
        sim = GrowthTraceTools.solver_output_to_dataframe(sol,names)
        sim = sim[sim.position .< max(sim.position...),:]
        sim[:,:lineage_original] = ones(length(sim.time)) .* lin
        sim[:,:replicate] = ones(length(sim.time)) .* i
        sim[:,:lineage] = ones(length(sim.time)) .* k
        sim[:,:ϕ] = ones(length(sim.time)) 
        push!(sims,sim)


        global k = k+1

        # -----------------------------------------------------------
        # DN Model
        # build model and run 
        θ = (Δ = Δ, σDN=σDN,τ = τDN,D=0 ,λ0 = λ0, σM = σM)
        println("    θ = ",θ)
        init = [θ.Δ,θ.λ0,2*θ.Δ]
        prob,callback,names = GrowthTraceTools.build_model_OU(θ,init,df.time)
        sol = solve(prob,EM(),callback = callback);

        # -----------------------------------------------------------
        # put in dataframe 
        sim = GrowthTraceTools.solver_output_to_dataframe(sol,names)
        sim = sim[sim.position .< max(sim.position...),:]
        sim[:,:lineage_original] = ones(length(sim.time)) .* lin
        sim[:,:replicate] = ones(length(sim.time)) .* i
        sim[:,:lineage] = ones(length(sim.time)) .* k
        sim[:,:ϕ] = zeros(length(sim.time)) 
        push!(sims,sim)
        global k = k+1
    end
end
sims = vcat(sims...);

CSV.write("./../output/sims_OUfit.csv",sims)